parameters:
    mandrill.client.class: Mandrill
    mandrill.dispatcher.class: FFreitasBr\MandrillBundle\Service\Dispatcher
    mandrill.dispatcher.factory.class: FFreitasBr\MandrillBundle\Component\Factory\DispatcherFactory

services:
    mandrill.dispatcher.abstract:
        class:          "%mandrill.dispatcher.class%"
        factory_class:  "%mandrill.dispatcher.factory.class%"
        factory_method: "create"
        abstract:       true

#
#    mandrill.client:
#        class: %hip_mandrill.client.class%
#        arguments: [%hip_mandrill.api_key%]
#
#    hip_mandrill.dispatcher:
#        class: %hip_mandrill.dispatcher.class%
#        arguments: [@hip_mandrill.client, %hip_mandrill.default.sender%, %hip_mandrill.default.sender_name%, %hip_mandrill.default.subaccount%, %hip_mandrill.disable_delivery%, %hip_mandrill.proxy%]
